# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(835, 563)
        mainWindow.setAcceptDrops(True)
        mainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        #self.centralwidget.setAcceptDrops(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 835, 27))
        self.menubar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        #self.menubar.setAcceptDrops(True)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setGeometry(QtCore.QRect(312, 266, 200, 200))
        self.menuFile.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.menuFile.setFont(font)
        self.menuFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.menuFile.setObjectName("menuFile")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.action_Open_2 = QtWidgets.QAction(mainWindow)
        self.action_Open_2.setObjectName("action_Open_2")
        self.action_Save = QtWidgets.QAction(mainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_SaveAs = QtWidgets.QAction(mainWindow)
        self.action_SaveAs.setObjectName("action_SaveAs")
        self.action_Close = QtWidgets.QAction(mainWindow)
        self.action_Close.setObjectName("action_Close")
        self.menuFile.addAction(self.action_Open_2)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_SaveAs)
        self.menuFile.addAction(self.action_Close)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Dex-Viewer"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.action_Open_2.setText(_translate("mainWindow", "Open"))
        self.action_Save.setText(_translate("mainWindow", "Save"))
        self.action_SaveAs.setText(_translate("mainWindow", "SaveAs"))
        self.action_Close.setText(_translate("mainWindow", "Close"))
